---
- name: Install extra packages
  hosts: all
  become: true
  tasks:

  - name: Install packages
    command: "rpm-ostree install {{ item }}"
    with_items:
      # socat is needed for Helm
      - socat

  - name: Reboot to make layered packages available
    shell: sleep 2 && systemctl reboot
    async: 1
    poll: 0

  - name: Wait for host to be available
    wait_for_connection:
      delay: 15

- name: Deploy K8S
  import_playbook: "kubespray/cluster.yml"
  vars:
    dns_mode: "coredns"
    docker_mount_flags: "shared"
    kube_network_plugin: "flannel"
    kube_version: "v1.13.1"
    local_volumes_enabled: true
    kube_feature_gates: ["VolumeSnapshotDataSource=true"]

- name: Fetch config
  hosts: kube-master[0]
  become: true
  tasks:
    - name: Retrieve kubectl config
      fetch:
        dest: ./kubeconfig
        flat: yes
        src: /root/.kube/config
