---
# Any specific customization required in the vagrant environment needs to be
# done in this play
- name: Pre-deploy bootstrapping
  hosts: all
  become: true
  gather_facts: false
  tags:
    - predeploy
  vars:
    kmods:
      - dm_mirror
      - dm_snapshot
      - dm_thin_pool

  tasks:
    - name: Extend root VG
      lvg:
        vg: atomicos
        pvs: /dev/vda2,/dev/vdb
        state: present

    - name: Extend the root LV and FS to occupy remaining space
      lvol:
        vg: atomicos
        lv: root
        size: 100%FREE
        resizefs: true
      tags: diskextend

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      with_items: "{{ kmods }}"

    - name: Persist loaded modules
      copy:
        dest: "/etc/modules-load.d/gluster-{{ item }}.conf"
        content: "{{ item }}"
      with_items: "{{ kmods }}"

    - name: Install packages
      command: "rpm-ostree install {{ item }}"
      with_items:
        # socat is needed for Helm
        - socat

    - name: Reboot to make layered packages available
      shell: sleep 2 && systemctl reboot
      async: 1
      poll: 0

    - name: Wait for host to be available
      wait_for_connection:
        delay: 15


- import_playbook: "./deploy-k8s.yml"
  vars:
    # local_release_dir needs to be set for atomic hosts.
    local_release_dir: "/var/vagrant/temp"
- import_playbook: "./deploy-gcs.yml"
